# Generated by Django 4.2.28 on 2026-02-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked')], default='pending', max_length=10, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Message from professional to owner explaining why access is needed.', verbose_name='request message')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, access is automatically revoked after this date.', null=True, verbose_name='access expires at')),
                ('can_view_medical', models.BooleanField(default=True, verbose_name='can view medical history')),
                ('can_add_medical', models.BooleanField(default=True, verbose_name='can add medical records')),
                ('can_add_services', models.BooleanField(default=True, verbose_name='can register services')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='animals.animal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='organizations.organization', verbose_name='organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='animal owner')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requesting professional')),
            ],
            options={
                'verbose_name': 'consent',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'animal')},
            },
        ),
        migrations.CreateModel(
            name='VetMedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('record_type', models.CharField(choices=[('checkup', 'Checkup'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery'), ('diagnosis', 'Diagnosis'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20, verbose_name='record type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('date_performed', models.DateField(verbose_name='date performed')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='next due date')),
                ('attachment', models.FileField(blank=True, upload_to='vet_records/%Y/%m/', verbose_name='attachment')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='animals.animal')),
                ('consent', models.ForeignKey(help_text='The consent under which this record was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.consent')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='organizations.organization', verbose_name='organization')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'veterinary medical record',
                'ordering': ['-date_performed'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service_name', models.CharField(max_length=255, verbose_name='service')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_provided', models.DateField(verbose_name='date provided')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='currency')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='animals.animal')),
                ('consent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.consent')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='organizations.organization', verbose_name='organization')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_provided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service record',
                'ordering': ['-date_provided'],
            },
        ),
    ]
