# Generated by Django 4.2.28 on 2026-02-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('reptile', 'Reptile'), ('other', 'Other')], max_length=20, verbose_name='species')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='breed')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='color')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='sex')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='neutered/spayed')),
                ('microchip_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='microchip ID')),
                ('photo', models.ImageField(blank=True, upload_to='animals/%Y/%m/', verbose_name='main photo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('medical_notes', models.TextField(blank=True, help_text='Private notes visible only to the owner and authorized vets.', verbose_name='medical notes (owner)')),
                ('is_lost', models.BooleanField(default=False, verbose_name='marked as lost')),
                ('lost_since', models.DateTimeField(blank=True, null=True, verbose_name='lost since')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='animals/gallery/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
            ],
            options={
                'verbose_name': 'animal photo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight (kg)')),
                ('date_recorded', models.DateField(verbose_name='date recorded')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='animals.animal')),
            ],
            options={
                'verbose_name': 'weight record',
                'verbose_name_plural': 'weight records',
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['animal', '-date_recorded'], name='weight_animal_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. Rabies, DHPP, FVRCP', max_length=200, verbose_name='vaccine name')),
                ('date_administered', models.DateField(verbose_name='date administered')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='next due date')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='batch/lot number')),
                ('administered_by', models.CharField(blank=True, help_text='Vet name or clinic', max_length=200, verbose_name='administered by')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
            ],
            options={
                'verbose_name': 'vaccination',
                'verbose_name_plural': 'vaccinations',
                'ordering': ['-date_administered'],
                'indexes': [models.Index(fields=['animal', '-date_administered'], name='vacc_animal_date_idx'), models.Index(fields=['next_due_date', 'reminder_sent'], name='vacc_due_reminder_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateField(verbose_name='appointment date')),
                ('time', models.TimeField(verbose_name='appointment time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='scheduled', max_length=10, verbose_name='status')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animals.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appointments', to=settings.AUTH_USER_MODEL, verbose_name='veterinarian')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['owner', 'date'], name='appointment_owner_date_idx'), models.Index(fields=['vet', 'date'], name='appointment_vet_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnimalCoOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'View & Edit'), ('manage', 'Full Manage')], default='view', max_length=10, verbose_name='permission level')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owners', to='animals.animal')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_animals', to=settings.AUTH_USER_MODEL, verbose_name='shared with')),
            ],
            options={
                'verbose_name': 'co-owner',
                'verbose_name_plural': 'co-owners',
                'unique_together': {('animal', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='animal_owner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['is_lost', 'is_active'], name='animal_lost_active_idx'),
        ),
    ]
