"""Invoice PDF generation using ReportLab."""

import io
import logging
from datetime import datetime

from django.conf import settings
from django.core.files.base import ContentFile
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)


def generate_invoice_number():
    """Generate a unique invoice number: LP-YYYYMMDD-NNNNN."""
    from .models import Invoice

    today = datetime.now().strftime("%Y%m%d")
    prefix = f"LP-{today}-"
    last = (
        Invoice.objects.filter(invoice_number__startswith=prefix)
        .order_by("-invoice_number")
        .first()
    )
    if last:
        seq = int(last.invoice_number.split("-")[-1]) + 1
    else:
        seq = 1
    return f"{prefix}{seq:05d}"


def generate_invoice_pdf(invoice):
    """Generate a PDF for the given Invoice and save it to the model."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "InvoiceTitle",
        parent=styles["Heading1"],
        fontSize=20,
        spaceAfter=12,
    )
    normal = styles["Normal"]

    elements = []

    # Header
    elements.append(Paragraph("Localipet", title_style))
    elements.append(
        Paragraph(
            f"<b>Invoice:</b> {invoice.invoice_number}",
            normal,
        )
    )
    elements.append(
        Paragraph(
            f"<b>Date:</b> {invoice.created_at.strftime('%Y-%m-%d')}",
            normal,
        )
    )
    elements.append(
        Paragraph(
            f"<b>Status:</b> {invoice.get_status_display()}",
            normal,
        )
    )
    elements.append(Spacer(1, 0.3 * inch))

    # Customer info
    user = invoice.user
    elements.append(Paragraph("<b>Bill To:</b>", normal))
    elements.append(Paragraph(user.get_full_name() or user.email, normal))
    elements.append(Paragraph(user.email, normal))
    if hasattr(user, "profile") and user.profile.address:
        elements.append(Paragraph(user.profile.address, normal))
    elements.append(Spacer(1, 0.3 * inch))

    # Items table
    if invoice.order:
        data = [["Product", "Qty", "Unit Price", "Subtotal"]]
        for item in invoice.order.items.select_related("product").all():
            data.append([
                item.product.name,
                str(item.quantity),
                f"${item.unit_price:,.2f}",
                f"${item.subtotal:,.2f}",
            ])
    else:
        data = [["Description", "", "", "Amount"]]
        data.append(["Subscription", "", "", f"${invoice.total:,.2f}"])

    # Totals
    data.append(["", "", "Subtotal:", f"${invoice.subtotal:,.2f}"])
    if invoice.tax > 0:
        data.append(["", "", "Tax:", f"${invoice.tax:,.2f}"])
    data.append(["", "", "Total:", f"${invoice.total:,.2f} {invoice.currency}"])

    table = Table(data, colWidths=[3.5 * inch, 0.8 * inch, 1.2 * inch, 1.2 * inch])
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4CAF50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -4), 0.5, colors.grey),
            ("LINEABOVE", (2, -3), (-1, -3), 1, colors.black),
            ("FONTNAME", (2, -1), (-1, -1), "Helvetica-Bold"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    elements.append(table)
    elements.append(Spacer(1, 0.5 * inch))

    # Footer
    elements.append(
        Paragraph(
            f"<i>Generated by Localipet — {settings.BASE_URL}</i>",
            ParagraphStyle("Footer", parent=normal, fontSize=8, textColor=colors.grey),
        )
    )

    doc.build(elements)

    # Save PDF to invoice model
    buf.seek(0)
    filename = f"invoice_{invoice.invoice_number}.pdf"
    invoice.pdf.save(filename, ContentFile(buf.read()), save=True)
    buf.close()

    logger.info("Generated PDF for invoice %s", invoice.invoice_number)
    return invoice


def create_invoice_for_order(order):
    """Create an Invoice for a paid Order and generate its PDF."""
    from .models import Invoice

    if hasattr(order, "invoice"):
        return order.invoice

    invoice_number = generate_invoice_number()
    subtotal = order.total
    tax = subtotal * settings.__dict__.get("TAX_RATE", 0)
    total = subtotal + tax

    invoice = Invoice.objects.create(
        order=order,
        user=order.user,
        invoice_number=invoice_number,
        subtotal=subtotal,
        tax=tax,
        total=total,
        currency=order.currency,
        status=Invoice.Status.PAID,
    )

    generate_invoice_pdf(invoice)
    return invoice
