# Generated by Django 4.2.28 on 2026-02-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('data_type', models.CharField(choices=[('scan_logs', 'Scan Logs'), ('audit_logs', 'Audit Logs'), ('inactive_accounts', 'Inactive Accounts'), ('expired_consents', 'Expired Consents'), ('cookie_consents', 'Cookie Consents'), ('deleted_animal_data', 'Deleted Animal Data')], max_length=30, unique=True, verbose_name='data type')),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days to retain this data type. 0 = keep forever.', verbose_name='retention period (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_cleanup', models.DateTimeField(blank=True, null=True, verbose_name='last cleanup')),
            ],
            options={
                'verbose_name': 'data retention policy',
                'verbose_name_plural': 'data retention policies',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doc_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy')], max_length=30, verbose_name='document type')),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash of the document content for integrity verification', max_length=64, verbose_name='content hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('changelog', models.TextField(blank=True, help_text='Summary of changes from previous version', verbose_name='changelog')),
            ],
            options={
                'verbose_name': 'legal document',
                'verbose_name_plural': 'legal documents',
                'ordering': ['-effective_date'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('consent_given', models.BooleanField(default=True, verbose_name='consent given')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='withdrawn at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='compliance.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legal consent',
                'verbose_name_plural': 'legal consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='session key')),
                ('essential', models.BooleanField(default=True, verbose_name='essential cookies')),
                ('analytics', models.BooleanField(default=False, verbose_name='analytics cookies')),
                ('marketing', models.BooleanField(default=False, verbose_name='marketing cookies')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cookie consent',
                'verbose_name_plural': 'cookie consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('consent_given', 'Consent Given'), ('consent_withdrawn', 'Consent Withdrawn'), ('data_export', 'Data Export Requested'), ('data_delete', 'Data Deletion Requested'), ('profile_update', 'Profile Updated'), ('password_change', 'Password Changed'), ('animal_created', 'Animal Created'), ('animal_deleted', 'Animal Deleted'), ('order_placed', 'Order Placed'), ('subscription_change', 'Subscription Changed')], max_length=30, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action', verbose_name='metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_date_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_date_idx')],
            },
        ),
    ]
