# Generated by Django 4.2.28 on 2026-02-23 09:14

import apps.scanning.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('token', models.CharField(db_index=True, default=apps.scanning.models.generate_scan_token, max_length=32, unique=True, verbose_name='scan token')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('qr_image', models.ImageField(blank=True, upload_to='qr_codes/%Y/%m/', verbose_name='QR image')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='animals.animal')),
            ],
            options={
                'verbose_name': 'QR code',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('city_guess', models.CharField(blank=True, max_length=100, verbose_name='approximate city')),
                ('country_guess', models.CharField(blank=True, max_length=100, verbose_name='approximate country')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanning.qrcode')),
            ],
            options={
                'verbose_name': 'scan log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tag_uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='NFC tag UID')),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='animals.animal')),
            ],
            options={
                'verbose_name': 'NFC tag',
            },
        ),
        migrations.CreateModel(
            name='FinderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sender_name', models.CharField(max_length=100, verbose_name='your name')),
                ('sender_phone', models.CharField(blank=True, max_length=30, verbose_name='your phone')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='your email')),
                ('message', models.TextField(max_length=1000, verbose_name='message')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finder_messages', to='scanning.qrcode')),
                ('scan_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='scanning.scanlog')),
            ],
            options={
                'verbose_name': 'finder message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['qr_code', '-created_at'], name='scanlog_qr_created_idx'),
        ),
    ]
