# Generated by Django 4.2.28 on 2026-02-23 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('model_name', models.CharField(help_text="Django model that was synced (e.g., 'Order').", max_length=100, verbose_name='model name')),
                ('local_id', models.CharField(help_text='UUID of the local object.', max_length=36, verbose_name='local ID')),
                ('odoo_id', models.IntegerField(blank=True, help_text='ID of the record in Odoo.', null=True, verbose_name='Odoo ID')),
                ('odoo_model', models.CharField(blank=True, help_text="Odoo model name (e.g., 'sale.order').", max_length=100, verbose_name='Odoo model')),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10, verbose_name='operation')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('request_data', models.JSONField(blank=True, help_text='Payload sent to Odoo.', null=True, verbose_name='request data')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='synced at')),
            ],
            options={
                'verbose_name': 'Odoo sync log',
                'verbose_name_plural': 'Odoo sync logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'local_id'], name='sync_model_local_idx'), models.Index(fields=['status', '-created_at'], name='sync_status_date_idx')],
            },
        ),
    ]
