# Generated by Django 4.2.28 on 2026-02-22 21:33

import apps.organizations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='organization name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('org_type', models.CharField(choices=[('vet_clinic', 'Veterinary Clinic'), ('pet_shop', 'Pet Shop'), ('shelter', 'Shelter')], max_length=20, verbose_name='type')),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/%Y/%m/', verbose_name='logo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP code')),
                ('country', models.CharField(default='MX', max_length=100, verbose_name='country')),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, help_text='Legal business name for invoicing', max_length=255, verbose_name='business name')),
                ('regimen_fiscal', models.CharField(blank=True, max_length=100, verbose_name='tax regime')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('odoo_partner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organizations.organization')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_registered', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization client',
                'verbose_name_plural': 'organization clients',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('max_staff', models.PositiveIntegerField(default=3, verbose_name='max staff members')),
                ('max_clients', models.PositiveIntegerField(default=50, verbose_name='max clients')),
                ('has_bulk_operations', models.BooleanField(default=False)),
                ('has_revenue_dashboard', models.BooleanField(default=False)),
                ('has_csv_import', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='0.10 = 10% commission on product sales', max_digits=5, verbose_name='commission rate')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'organization plan',
                'verbose_name_plural': 'organization plans',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stripe_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(null=True)),
                ('current_period_end', models.DateTimeField(null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organizationplan')),
            ],
            options={
                'verbose_name': 'organization subscription',
                'verbose_name_plural': 'organization subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, verbose_name='invited email')),
                ('invite_type', models.CharField(choices=[('staff', 'Staff Member'), ('client', 'Client')], max_length=10)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('vet', 'Veterinarian')], help_text='Only for staff invitations', max_length=10, verbose_name='role')),
                ('token', models.CharField(db_index=True, default=apps.organizations.models._generate_invite_token, max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='organizations.organizationclient')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_sale', to='billing.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='organizations.organization')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization sale',
                'verbose_name_plural': 'organization sales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='orgsale_org_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('vet', 'Veterinarian')], max_length=10, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization member',
                'verbose_name_plural': 'organization members',
                'indexes': [models.Index(fields=['user', 'is_active'], name='orgmember_user_active_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='organizationclient',
            index=models.Index(fields=['organization', 'is_active'], name='orgclient_org_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationclient',
            unique_together={('organization', 'user')},
        ),
    ]
