# Generated by Django 4.2.28 on 2026-02-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notification_type', models.CharField(choices=[('scan_alert', 'QR Scan Alert'), ('finder_message', 'Finder Message'), ('consent_request', 'Consent Request'), ('consent_response', 'Consent Response'), ('consent_revoked', 'Consent Revoked'), ('order_status', 'Order Status Update'), ('subscription', 'Subscription Update'), ('reminder', 'Reminder'), ('system', 'System Notification')], max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('url', models.CharField(blank=True, help_text='URL to redirect when notification is clicked.', max_length=500, verbose_name='action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx')],
            },
        ),
    ]
